### ISSUE TITLE
Package hacs setup failed. Component hacs unable to import

### ISSUE THREAD

**Issue by Sjeff** [custom-components/hacs#37]
## Version of HACS

Trying to update from 0.2.1 to 0.4.1

## Describe the bug
After updating i receive this message when i check the home assistant config.

![Capture](https://user-images.githubusercontent.com/11430228/58753488-2ae8d500-84c0-11e9-9ece-8a78624c68a6.JPG)

Removed all hacs files and downloaded the latest version again. 
Getting the same error.

HA version : 0.93.2
Docker running on Ubuntu.

## Debug log

```text

No logs found.....

```

**Comment by r3mcos3** [comment]
I'm also working with packages.
But when i put 
hacs: 
  token: !secret my_token 
In the configuration.yaml it worked

**Comment by Sjeff** [comment]
yeah thats what i have.
```
hacs:
  token: !secret my_github_access_token
```

worked with version 0.2.1

**Comment by r3mcos3** [comment]
Ok than i don't know

**Comment by Sjeff** [comment]
I use a split config file.
Just revert back to v 0.2.1 all working again.

**Comment by r3mcos3** [comment]
That was my problem to,
I have a split config but when I added the HACS component direct to the configuration.yaml it start to work.

My configuration.yaml
```
---
homeassistant:
  # Name of this Home Assistant instance... I've tried to be original... ;)
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

  # Load packages
  packages: !include_dir_named integrations

  whitelist_external_dirs:
    - /config
    
hacs:
  token: !secret hacs_token

```
